In [ ]:
!pip install catboost

In [ ]:
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split

In [ ]:
match_data = match_data.drop(['winner', 'match id', 'match_dt', 'team1_roster_ids', 'team2_roster_ids'], axis=1)

In [ ]:
# Shuffling dataset

match_data = match_data.sample(frac=1, random_state=1234)

In [ ]:
match_data.shape

(1689, 154)

In [ ]:
1689/3

563.0

In [ ]:
# I have separted the data along columns and to be used to train 3 separate models.
# These 3 models will be then combined and then trained as a combined meta-model that contains all column features.
# I have combined the data into as train, validation and test splits.
# X_train will be used to train the 3 initial models.
# X_val will be used to train the combined meta model.
# X_test will be used to check the accuracy of the final model.
# Each dataset X_train, X_val and X_test will be splitted to train and validation sets for training their respective model.

X_train = match_data[:563]                      # small models training
X_val = match_data[563:832]                     # meta model training
X_test = match_data[832:]                       # test set
y_train = X_train['winner_team1']
y_val = X_val['winner_team1']
y_test = X_test['winner_team1']

In [ ]:
match_1 = X_train[['team1_rf', 'team1_rfm','team1_l', 'team1_lf', 'team1_lfm', 'team1_lg','team2_lhb', 'team2_lm',
                  'team1_lmf', 'team1_ls', 'team1_lsm', 'team1_lws',  'team2_l', 'team2_lbw', 'team2_lf', 'team2_lg',
                  'team2_ls', 'team2_lsm', 'team2_lws', 'team2_rmf','team2_ro','team1_lbw','team2_rhb', 'team1_slo', 'team2_slo',
                  'team1_rhb','team1_ro','team2_rm','team2_lfm','team2_rfm','team2_rf','team1_lhb','team1_lm','team2_lmf',
                   'by','city','win amount','umpire1','umpire2','venue','win_pct_3', 'team1_id', 'team2_id',
                  'ground_avg_wickets', 'ground_avg_runs','ground_id', 'lighting',
                  'season', 'series_name', 'series_type', 'winner_1st_bat','toss decision','toss winner',
                  ]]

match_2 = X_train[['team1_runs','team2_runs','team1_balls','team2_avg_runs_last3','team1_fours','team2_caught',
                  'team2_wides','team2_boundary_rate','team2_sixes','team2_bowling_avg','team1_batting_avg','team1_no_50s_last3','team1_wickets',
                   'team2_balls','team2_wicket_count','team2_fours','team1_sixes','team1_wides','team2_fifties','team2_wickets',
                  'team1_runs_conceded','team1_maiden','team2_batting_avg','team1_bowling_avg', 'team1_strike_rate','team2_avg_wickets_last3',
                  'team1_boundary_rate','team1_avg_wickets_last3','team2_century', 'team2_dots','team1_4_wicket_hauls', 'team1_5_wicket_hauls',
                   'team1_avg_runs_last3', 'team1_bowled', 'team1_caught_bowled','team1_century', 'team1_dots', 'team1_economy',
                   'team1_fifties', 'team1_hit_wicket', 'team1_wicket_count','team2_4_wicket_hauls','team2_5_wicket_hauls','team2_maiden',
                   'team2_no_50s_last3','team2_runs_conceded','team2_strike_rate','team1_noballs', 'team1_not_out', 'team1_retired_hurt',
                   'team1_retired_not_out', 'team1_retired_out','team2_retired_out','team2_noballs','team2_retired_hurt','team2_retired_not_out',
                   'team1_rm', 'team1_rmf', 'team1_runout', 'team1_stumped', 'team2_bowled',
                   'team2_caught_bowled',  'team2_hit_wicket','team2_runout','team2_stumped','team2_not_out','team1_caught'
                   ]]

match_3 = X_train[['diff_century', 'diff_dots', 'diff_fours', 'diff_maiden', 'diff_wicket_count', 'diff_wickets','diff_sixes',
                   'diff_4_wicket_hauls', 'diff_5_wicket_hauls', 'diff_avg_runs_last3','diff_strike_rate','diff_noballs','diff_boundary_rate',
                   'diff_avg_wickets_last3', 'diff_batting_avg','diff_not_out','diff_no_50s_last3','diff_runs','diff_bowling_avg',
                   'diff_runs_conceded', 'diff_economy', 'diff_wides','diff_balls','diff_fifties']]

In [ ]:
match_4 = X_val.drop('winner_team1', axis=1)

**model 1**

In [ ]:
cat_features_1 = ['toss decision', 'venue', 'lighting', 'series_name', 'season', 'series_type', 'ground_id',
                  'toss winner', 'by', 'city', 'umpire1', 'umpire2', 'team1_id', 'team2_id', 'winner_1st_bat']

In [ ]:
X_1 = match_1
y_1 = y_train

X_train_1, X_validation_1, y_train_1, y_validation_1 = train_test_split(X_1, y_1, train_size=0.7, random_state=1234)
X_val_1, X_test_1, y_val_1, y_test_1 = train_test_split(X_validation_1, y_validation_1, train_size=0.5, random_state=1234)
model_1 = CatBoostClassifier(verbose=100)
model_1.fit(X_train_1, y_train_1, eval_set=(X_val_1, y_val_1))

Learning rate set to 0.025177
0:	learn: 0.6401898	test: 0.6399038	best: 0.6399038 (0)	total: 3.22ms	remaining: 3.22s
100:	learn: 0.0079788	test: 0.0082435	best: 0.0082435 (100)	total: 219ms	remaining: 1.95s
200:	learn: 0.0023942	test: 0.0024496	best: 0.0024496 (200)	total: 448ms	remaining: 1.78s
300:	learn: 0.0013699	test: 0.0013987	best: 0.0013987 (300)	total: 679ms	remaining: 1.57s
400:	learn: 0.0011064	test: 0.0011392	best: 0.0011392 (400)	total: 1.11s	remaining: 1.66s
500:	learn: 0.0010171	test: 0.0010572	best: 0.0010572 (500)	total: 1.66s	remaining: 1.65s
600:	learn: 0.0009797	test: 0.0010224	best: 0.0010224 (593)	total: 2.13s	remaining: 1.41s
700:	learn: 0.0009797	test: 0.0010224	best: 0.0010224 (593)	total: 2.64s	remaining: 1.13s
800:	learn: 0.0009797	test: 0.0010224	best: 0.0010224 (593)	total: 3.15s	remaining: 783ms
900:	learn: 0.0009670	test: 0.0010105	best: 0.0010105 (878)	total: 3.64s	remaining: 400ms
999:	learn: 0.0009670	test: 0.0010105	best: 0.0010105 (878)	total: 4.14s	

In [ ]:
def print_feature_importance(feature_importances, feature_names):

    feature_importance_pairs = [(feature_names[i], importance) for i, importance in enumerate(feature_importances)]
    feature_importance_pairs = sorted(feature_importance_pairs, key=lambda x: x[1], reverse=True)
    print("Feature Importance (Descending Order):")
    for feature_name, importance in feature_importance_pairs:
        print(f"{feature_name}: {importance}")

print_feature_importance(model_1.feature_importances_, X_train_1.columns)

Feature Importance (Descending Order):
winner_1st_bat: 56.11991541260103
by: 35.93629816506745
venue: 0.34716094772012884
ground_avg_runs: 0.29160148413504505
team2_lfm: 0.2863040735504059
toss winner: 0.2793208035918539
team1_ro: 0.2736596523095324
team1_lg: 0.27305891515989367
umpire1: 0.2653612299065407
team2_ro: 0.2635528156713413
series_name: 0.2533898248039433
season: 0.24973884910571856
team1_lfm: 0.24946132504949364
team1_rfm: 0.23400482059744984
team2_lf: 0.22909699222351487
team2_rf: 0.22887839350358882
team2_l: 0.2287068750168005
team2_lws: 0.22567342094852375
team2_slo: 0.22438993031339866
team2_lg: 0.2140361119904645
team2_lmf: 0.2135644284452269
umpire2: 0.19962338012932737
team1_id: 0.19421503507121404
team1_slo: 0.1911353754973239
win amount: 0.17737840678610067
team2_rmf: 0.17260701759664418
win_pct_3: 0.16976261229682402
series_type: 0.16858140098507296
team1_lmf: 0.16644057868604165
team2_rfm: 0.16085961727385842
team1_rf: 0.15756292802376232
team2_rm: 0.145153689815

In [ ]:
from sklearn.metrics import confusion_matrix

y_pred_1 = model_1.predict(X_test_1)
cm = confusion_matrix(y_test_1, y_pred_1)
print(cm)

[[48  0]
 [ 0 37]]


**model 2**

In [ ]:
X_2 = match_2
y_2 = y_train

X_train_2, X_validation_2, y_train_2, y_validation_2 = train_test_split(X_2, y_2, train_size=0.7, random_state=7544)
X_val_2, X_test_2, y_val_2, y_test_2 = train_test_split(X_validation_2, y_validation_2, train_size=0.5, random_state=877)
model_2 = CatBoostClassifier(verbose=100)
model_2.fit(X_train_2, y_train_2, eval_set=(X_val_2, y_val_2))

Learning rate set to 0.025177
0:	learn: 0.6651119	test: 0.6626481	best: 0.6626481 (0)	total: 3.3ms	remaining: 3.3s
100:	learn: 0.1260374	test: 0.1795804	best: 0.1795804 (100)	total: 230ms	remaining: 2.05s
200:	learn: 0.0660778	test: 0.1558850	best: 0.1553806 (192)	total: 477ms	remaining: 1.89s
300:	learn: 0.0391917	test: 0.1588111	best: 0.1553806 (192)	total: 711ms	remaining: 1.65s
400:	learn: 0.0240760	test: 0.1564609	best: 0.1545731 (359)	total: 952ms	remaining: 1.42s
500:	learn: 0.0173447	test: 0.1583156	best: 0.1545731 (359)	total: 1.18s	remaining: 1.18s
600:	learn: 0.0134691	test: 0.1598578	best: 0.1545731 (359)	total: 1.43s	remaining: 952ms
700:	learn: 0.0112687	test: 0.1635393	best: 0.1545731 (359)	total: 1.67s	remaining: 711ms
800:	learn: 0.0096510	test: 0.1678914	best: 0.1545731 (359)	total: 1.89s	remaining: 470ms
900:	learn: 0.0080945	test: 0.1706627	best: 0.1545731 (359)	total: 2.13s	remaining: 234ms
999:	learn: 0.0070108	test: 0.1716073	best: 0.1545731 (359)	total: 2.37s	re

In [ ]:
def print_feature_importance(feature_importances, feature_names):

    feature_importance_pairs = [(feature_names[i], importance) for i, importance in enumerate(feature_importances)]
    feature_importance_pairs = sorted(feature_importance_pairs, key=lambda x: x[1], reverse=True)
    print("Feature Importance (Descending Order):")
    for feature_name, importance in feature_importance_pairs:
        print(f"{feature_name}: {importance}")

print_feature_importance(model_2.feature_importances_, X_train_2.columns)

Feature Importance (Descending Order):
team1_bowling_avg: 20.285879570367484
team1_wickets: 14.01491634975487
team1_balls: 13.74155746248886
team2_runs: 10.804571670867402
team1_runs: 7.466312871834229
team1_batting_avg: 7.290784295528973
team2_batting_avg: 5.6433121407229985
team2_bowling_avg: 3.8632928423018438
team2_avg_runs_last3: 2.695796992593068
team1_avg_runs_last3: 2.247132554048744
team1_avg_wickets_last3: 2.232646675046583
team2_balls: 1.806548317928784
team2_wickets: 1.699884590043164
team2_avg_wickets_last3: 1.527113112323558
team1_no_50s_last3: 1.4321014542895547
team1_rm: 1.3182685658631181
team1_rmf: 1.0335094909823548
team2_no_50s_last3: 0.8963710430144021
team1_fours: 0.0
team2_caught: 0.0
team2_wides: 0.0
team2_boundary_rate: 0.0
team2_sixes: 0.0
team2_wicket_count: 0.0
team2_fours: 0.0
team1_sixes: 0.0
team1_wides: 0.0
team2_fifties: 0.0
team1_runs_conceded: 0.0
team1_maiden: 0.0
team1_strike_rate: 0.0
team1_boundary_rate: 0.0
team2_century: 0.0
team2_dots: 0.0
team

In [ ]:
from sklearn.metrics import confusion_matrix

y_pred_2 = model_2.predict(X_test_2)
cm = confusion_matrix(y_test_2, y_pred_2)
print(cm)

[[48  5]
 [ 2 30]]


**model 3**

In [ ]:
X_3 = match_3
y_3 = y_train

X_train_3, X_validation_3, y_train_3, y_validation_3 = train_test_split(X_3, y_3, train_size=0.7, random_state=7544)
X_val_3, X_test_3, y_val_3, y_test_3 = train_test_split(X_validation_3, y_validation_3, train_size=0.5, random_state=877)
model_3 = CatBoostClassifier(verbose=100)
model_3.fit(X_train_3, y_train_3, eval_set=(X_val_3, y_val_3))

Learning rate set to 0.025177
0:	learn: 0.6476595	test: 0.6440030	best: 0.6440030 (0)	total: 1.81ms	remaining: 1.81s
100:	learn: 0.0145259	test: 0.0113109	best: 0.0113109 (100)	total: 149ms	remaining: 1.32s
200:	learn: 0.0049832	test: 0.0040813	best: 0.0040813 (200)	total: 302ms	remaining: 1.2s
300:	learn: 0.0031374	test: 0.0026577	best: 0.0026577 (300)	total: 437ms	remaining: 1.01s
400:	learn: 0.0020677	test: 0.0018454	best: 0.0018449 (399)	total: 584ms	remaining: 873ms
500:	learn: 0.0017178	test: 0.0015956	best: 0.0015954 (498)	total: 736ms	remaining: 733ms
600:	learn: 0.0015397	test: 0.0014978	best: 0.0014929 (561)	total: 903ms	remaining: 599ms
700:	learn: 0.0014954	test: 0.0014908	best: 0.0014899 (690)	total: 1.15s	remaining: 489ms
800:	learn: 0.0014579	test: 0.0014895	best: 0.0014891 (728)	total: 1.47s	remaining: 366ms
900:	learn: 0.0014433	test: 0.0014884	best: 0.0014878 (870)	total: 1.76s	remaining: 194ms
999:	learn: 0.0014336	test: 0.0014915	best: 0.0014878 (870)	total: 2.1s	re

In [ ]:
def print_feature_importance(feature_importances, feature_names):

    feature_importance_pairs = [(feature_names[i], importance) for i, importance in enumerate(feature_importances)]
    feature_importance_pairs = sorted(feature_importance_pairs, key=lambda x: x[1], reverse=True)
    print("Feature Importance (Descending Order):")
    for feature_name, importance in feature_importance_pairs:
        print(f"{feature_name}: {importance}")

print_feature_importance(model_3.feature_importances_, X_train_3.columns)

Feature Importance (Descending Order):
diff_runs: 85.21751750122871
diff_bowling_avg: 4.042918319303639
diff_balls: 2.872454802365182
diff_avg_wickets_last3: 2.3962285710566777
diff_wickets: 1.559262835292169
diff_batting_avg: 1.5129859276738256
diff_avg_runs_last3: 1.4693551342763385
diff_no_50s_last3: 0.9292769088034659
diff_century: 0.0
diff_dots: 0.0
diff_fours: 0.0
diff_maiden: 0.0
diff_wicket_count: 0.0
diff_sixes: 0.0
diff_4_wicket_hauls: 0.0
diff_5_wicket_hauls: 0.0
diff_strike_rate: 0.0
diff_noballs: 0.0
diff_boundary_rate: 0.0
diff_not_out: 0.0
diff_runs_conceded: 0.0
diff_economy: 0.0
diff_wides: 0.0
diff_fifties: 0.0


In [ ]:
from sklearn.metrics import confusion_matrix

y_pred_3 = model_3.predict(X_test_3)
cm = confusion_matrix(y_test_3, y_pred_3)
print(cm)

[[53  0]
 [ 0 32]]


**Combining models 1, 2 and 3**

In [ ]:
# Using X_val to train combined model

x1 = X_val[['team1_rf', 'team1_rfm','team1_l', 'team1_lf', 'team1_lfm', 'team1_lg','team2_lhb', 'team2_lm',
            'team1_lmf', 'team1_ls', 'team1_lsm', 'team1_lws',  'team2_l', 'team2_lbw', 'team2_lf', 'team2_lg',
            'team2_ls', 'team2_lsm', 'team2_lws', 'team2_rmf','team2_ro','team1_lbw','team2_rhb', 'team1_slo', 'team2_slo',
            'team1_rhb','team1_ro','team2_rm','team2_lfm','team2_rfm','team2_rf','team1_lhb','team1_lm','team2_lmf',
            'by','city','win amount','umpire1','umpire2','venue','win_pct_3',
            'ground_avg_wickets', 'ground_avg_runs','ground_id', 'lighting', 'team1_id', 'team2_id',
            'season', 'series_name', 'series_type',  'winner_1st_bat','toss decision','toss winner',
            ]]
x2= X_val[['team1_runs','team2_runs','team1_balls','team2_avg_runs_last3','team1_fours','team2_caught',
           'team2_wides','team2_boundary_rate','team2_sixes','team2_bowling_avg','team1_batting_avg','team1_no_50s_last3','team1_wickets',
           'team2_balls','team2_wicket_count','team2_fours','team1_sixes','team1_wides','team2_fifties','team2_wickets',
           'team1_runs_conceded','team1_maiden','team2_batting_avg','team1_bowling_avg', 'team1_strike_rate','team2_avg_wickets_last3',
           'team1_boundary_rate','team1_avg_wickets_last3','team2_century', 'team2_dots','team1_4_wicket_hauls', 'team1_5_wicket_hauls',
           'team1_avg_runs_last3', 'team1_bowled', 'team1_caught_bowled','team1_century', 'team1_dots', 'team1_economy',
           'team1_fifties', 'team1_hit_wicket', 'team1_wicket_count','team2_4_wicket_hauls','team2_5_wicket_hauls','team2_maiden',
           'team2_no_50s_last3','team2_runs_conceded','team2_strike_rate','team1_noballs', 'team1_not_out', 'team1_retired_hurt',
           'team1_retired_not_out', 'team1_retired_out','team2_retired_out','team2_noballs','team2_retired_hurt','team2_retired_not_out',
           'team1_rm', 'team1_rmf', 'team1_runout', 'team1_stumped', 'team2_bowled',
           'team2_caught_bowled',  'team2_hit_wicket','team2_runout','team2_stumped','team2_not_out','team1_caught'
            ]]
x3 = X_val[['diff_century', 'diff_dots', 'diff_fours', 'diff_maiden', 'diff_wicket_count', 'diff_wickets','diff_sixes',
            'diff_4_wicket_hauls', 'diff_5_wicket_hauls', 'diff_avg_runs_last3','diff_strike_rate','diff_noballs','diff_boundary_rate',
            'diff_avg_wickets_last3', 'diff_batting_avg','diff_not_out','diff_no_50s_last3','diff_runs','diff_bowling_avg',
            'diff_runs_conceded', 'diff_economy', 'diff_wides','diff_balls','diff_fifties'
            ]]

In [ ]:
# Prediction of models 1, 2 and 3 on X_val will be combined and this will be the training data for the meta-model.

pred_1 = model_1.predict(x1)
pred_2 = model_2.predict(x2)
pred_3 = model_3.predict(x3)

In [ ]:
# Combining predictions

combined_predictions = np.vstack((pred_1, pred_2, pred_3)).T

In [ ]:
# Using Gradient Boosting Classifier for training the meta model

from sklearn.ensemble import GradientBoostingClassifier

meta_model = GradientBoostingClassifier().fit(combined_predictions, y_val)
final_predictions = meta_model.predict(combined_predictions)

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(final_predictions, y_val)
print(cm)

[[129   0]
 [  1 139]]


In [ ]:
# Now testing the final model using X_test

x1_test = X_test[['team1_rf', 'team1_rfm','team1_l', 'team1_lf', 'team1_lfm', 'team1_lg','team2_lhb', 'team2_lm',
                  'team1_lmf', 'team1_ls', 'team1_lsm', 'team1_lws',  'team2_l', 'team2_lbw', 'team2_lf', 'team2_lg',
                  'team2_ls', 'team2_lsm', 'team2_lws', 'team2_rmf','team2_ro','team1_lbw','team2_rhb', 'team1_slo', 'team2_slo',
                  'team1_rhb','team1_ro','team2_rm','team2_lfm','team2_rfm','team2_rf','team1_lhb','team1_lm','team2_lmf',
                   'by','city','win amount','umpire1','umpire2','venue','win_pct_3',
                  'ground_avg_wickets', 'ground_avg_runs','ground_id', 'lighting', 'team1_id', 'team2_id',
                  'season', 'series_name', 'series_type',  'winner_1st_bat','toss decision','toss winner',
                  ]]

x2_test = X_test[['team1_runs','team2_runs','team1_balls','team2_avg_runs_last3','team1_fours','team2_caught',
                  'team2_wides','team2_boundary_rate','team2_sixes','team2_bowling_avg','team1_batting_avg','team1_no_50s_last3','team1_wickets',
                   'team2_balls','team2_wicket_count','team2_fours','team1_sixes','team1_wides','team2_fifties','team2_wickets',
                  'team1_runs_conceded','team1_maiden','team2_batting_avg','team1_bowling_avg', 'team1_strike_rate','team2_avg_wickets_last3',
                  'team1_boundary_rate','team1_avg_wickets_last3','team2_century', 'team2_dots','team1_4_wicket_hauls', 'team1_5_wicket_hauls',
                   'team1_avg_runs_last3', 'team1_bowled', 'team1_caught_bowled','team1_century', 'team1_dots', 'team1_economy',
                   'team1_fifties', 'team1_hit_wicket', 'team1_wicket_count','team2_4_wicket_hauls','team2_5_wicket_hauls','team2_maiden',
                   'team2_no_50s_last3','team2_runs_conceded','team2_strike_rate','team1_noballs', 'team1_not_out', 'team1_retired_hurt',
                   'team1_retired_not_out', 'team1_retired_out','team2_retired_out','team2_noballs','team2_retired_hurt','team2_retired_not_out',
                   'team1_rm', 'team1_rmf', 'team1_runout', 'team1_stumped', 'team2_bowled',
                   'team2_caught_bowled',  'team2_hit_wicket','team2_runout','team2_stumped','team2_not_out','team1_caught'
                   ]]
x3_test = X_test[['diff_century', 'diff_dots', 'diff_fours', 'diff_maiden', 'diff_wicket_count', 'diff_wickets','diff_sixes',
                   'diff_4_wicket_hauls', 'diff_5_wicket_hauls', 'diff_avg_runs_last3','diff_strike_rate','diff_noballs','diff_boundary_rate',
                   'diff_avg_wickets_last3', 'diff_batting_avg','diff_not_out','diff_no_50s_last3','diff_runs','diff_bowling_avg',
                   'diff_runs_conceded', 'diff_economy', 'diff_wides','diff_balls','diff_fifties'
                   ]]

pred_1 = model_1.predict(x1_test)
pred_2 = model_2.predict(x2_test)
pred_3 = model_3.predict(x3_test)

combined_predictions = np.vstack((pred_1, pred_2, pred_3)).T

final_predictions = meta_model.predict(combined_predictions)

cm = confusion_matrix(final_predictions, y_test)
print(cm)

[[443   0]
 [  0 414]]
